### ISSUE TITLE
Target does not exist(running)

### ISSUE THREAD

**Issue by lexasub** [troldal/OpenXLSX#10]
code:
std::setlocale(LC_ALL, "ru_RU.UTF-8");
std::string filename="/home/file.xlsx";
 XLDocument doc;
 doc.OpenDocument(filename);
err:
terminate called after throwing an instance of 'OpenXLSX::XLException'
  what():  Target does not exist!

**Comment by troldal** [comment]
I was not able to recreate the error you report. It may have something to do with the input file you use ("file.xlsx"); since I don't have it, I am not able to identify the cause.
I tried to use doc.CreateDocument instead and it works fine.

**However...**
The std::setlocale resets the global locale (Russian, in the example above). That means that many standard functions will behave differently, for example the std::to_string function. With the Russian locale, an input of 3.14159 to the std::to_string function will yield a string "3,14159"...using comma instead of dot as the decimal separator. 
The XLSX file format, which is based on XML files, requires dots as decimal separators. Comma will not work. Therefore, the std::setlocale should **not** be used with OpenXLSX. Note that this is not a bug in OpenXLSX, but rather a limitation of the XLSX file format.

If locales are needed, try using C++ locale objects (found in the <locale> header) instead of using the global C locale as you have done above.

**Comment by lexasub** [comment]
I found that google docs does not compress xlsx and the file is not perceived by the library. but using an online converter I can get a working library
