### ISSUE TITLE
When using multiple threads, an error occurs，but using only one thread is ok

### ISSUE THREAD

**Issue by qq523915712** [troldal/OpenXLSX#120]
When using multiple threads, an error occurs，but using only one thread is ok.

**Comment by troldal** [comment]
OpenXLSX is not thread safe, so you shouldn't attempt to access the same document from multiple threads.
It may be possible to different documents from separate threads, but I haven't tried that.

OpenXLSX is not a database system for contiouous read/write access, and since it is fairly fast in single-threaded applications, I don't have any intentions of making it thread safe.
