### ISSUE TITLE
defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification

### ISSUE THREAD

**Issue by AlanYiNew** [troldal/OpenXLSX#201]
Compile on gcc version 8.3.1. Can the no except = default declaration defined in header only? I can't compile the lib under linux but ok with mingw

**Comment by aral-matrix** [comment]
I don't fully understand the issue, especially since I have been working exclusively on debian for a good half year now without problems - I am assuming that what you experienced is superseded by the code changes in the past half year. If you could test it & open a new issue should you still have problems, I would appreciate a few steps to reproduce / exact compiler errors.

**Comment by shanehou** [comment]
You don't need to write `SomeClass& operator=(SomeClass&& other) noexcept = default` in cpp file. Just write `=default` in hpp file is enough.

**Comment by aral-matrix** [comment]
> You don't need to write `SomeClass& operator=(SomeClass&& other) noexcept = default` in cpp file. Just write `=default` in hpp file is enough.

Not sure how you meant that - you still need to identify the function return type, name & parameters to clarify which one will be defaulted, no?
Anyways, I will have to remove nearly all =default statements now because of the use of forward declarations & smart pointers for XLXmlParser components.
