### ISSUE TITLE
Work sheet is misidentified as XLChartSheet

### ISSUE THREAD

**Issue by fauder** [troldal/OpenXLSX#264]
Hi,

I'm sharing an example .xlsx file, with 1 sheet in it. The sheet does not contain any charts but it is classified as XLChartSheet by OpenXLSX, instead of XLWorkSheet.

I looked at the source code and found this function:
```
XLSheetType XLWorkbook::typeOfSheet(const std::string& sheetName) const
{
    if (!sheetExists(sheetName)) throw XLInputError("Sheet with name \"" + sheetName + "\" doesn't exist.");

    if (worksheetExists(sheetName)) return XLSheetType::Worksheet;
    return XLSheetType::Chartsheet;
}
```

I'm guessing that `worksheetExists()` has a bug where it fails to deduce that the sheet is a proper work sheet.

Or there is some chart in the sheet that I can't see 😅

P.S.: I know that the chart sheet is largely unimplemented but if I cast the sheet()'s return value to XLWorkSheet and use it, there are no problems (just reading the file, no writes). Code example:

`auto sheet = ( OpenXLSX::XLWorksheet* )&doc.workbook().sheet( 0 );`

Is this OK?

[example_sheet.xlsx](https://github.com/user-attachments/files/16798305/example_sheet.xlsx)

**Comment by aral-matrix** [comment]
Merhaba @fauder 

thank you for providing an example XLSX file with your issue report, that way I was able to reproduce the issue quickly & create a fix. The underlying problem was that your XLSX does not use the domains expected for document relationships - I had previously not seen a document with deviating relationship domains in the wild. Please check out the [latest commit](https://github.com/troldal/OpenXLSX/commit/670b55cce8adf8f8846f86aa23f0bf8d8a8c2bbf) which addresses your issue. With this patch, I was able to open your example file and access the worksheet (and correctly determine the worksheet type with
```
	XLSheetType sheetType = doc.workbook().typeOfSheet("sheet");
```

İstediğin başka bir şey varsa, haber ver lütfen :) Kolay gelsin!

   /Lars

**Comment by fauder** [comment]
@aral-matrix Thanks/teşekkürler :)
I'll try it out now.

**Comment by fauder** [comment]
Tested the latest commit and it works without any issues. Thanks again 🤝

**Comment by aral-matrix** [comment]
Harika! Yeni sürümün, istediğine göre çalışmadığına sevindim :)
