### ISSUE TITLE
don't support korean?

### ISSUE THREAD

**Issue by Sangwook-Hwang** [troldal/OpenXLSX#27]
Invalid characters in string.

**Comment by rageworx** [comment]
https://github.com/troldal/OpenXLSX/tree/master#unicode

**Comment by troldal** [comment]
As @rageworx highlights, the string must be in UTF-8 format. Here is a piece of code that works on my machine:

```cpp
#include <iostream>
#include <OpenXLSX/OpenXLSX.h>

using namespace std;
using namespace OpenXLSX;

int main() {

    XLDocument doc1;
    doc1.CreateDocument("./UnicodeTest.xlsx");
    auto wks1 = doc1.Workbook().Worksheet("Sheet1");

    wks1.Cell("A1").Value() = "안녕하세요 세계!";
    wks1.Cell("A2").Value() = "你好，世界!";
    wks1.Cell("A3").Value() = "こんにちは世界";
    wks1.Cell("A4").Value() = "नमस्ते दुनिया!";
    wks1.Cell("A5").Value() = "Привет, мир!";
    wks1.Cell("A6").Value() = "Γειά σου Κόσμε!";

    doc1.SaveDocument();
    doc1.CloseDocument();

    XLDocument doc2;
    doc2.OpenDocument("./UnicodeTest.xlsx");
    auto wks2 = doc2.Workbook().Worksheet("Sheet1");

    cout << "Cell A1: " << wks2.Cell("A1").Value().Get<std::string>() << endl;
    cout << "Cell A2: " << wks2.Cell("A2").Value().Get<std::string>() << endl;
    cout << "Cell A3: " << wks2.Cell("A3").Value().Get<std::string>() << endl;
    cout << "Cell A4: " << wks2.Cell("A4").Value().Get<std::string>() << endl;
    cout << "Cell A5: " << wks2.Cell("A5").Value().Get<std::string>() << endl;
    cout << "Cell A6: " << wks2.Cell("A6").Value().Get<std::string>() << endl;

    doc2.CloseDocument();

    return 0;
}
```

The console output of this is:

```
Cell A1: 안녕하세요 세계!
Cell A2: 你好，世界!
Cell A3: こんにちは世界
Cell A4: नमस्ते दुनिया!
Cell A5: Привет, мир!
Cell A6: Γειά σου Κόσμε!

Process finished with exit code 0
```

I have also added the resulting spreadsheet.

[UnicodeTest.xlsx](https://github.com/troldal/OpenXLSX/files/4191249/UnicodeTest.xlsx)

If you still cannot get it to work, please provide a code sample.

**Comment by rageworx** [comment]
@troldal , I think @Sangwook-Hwang  may using MSVC and that's not handles UTF-8 encoded string at compilation.

**Comment by troldal** [comment]
I just tried compiling the code above on Windows 10 using MSVC/Visual Studio 2019. Outputting to console results in gibberish, but the resulting .xlsx spreadsheet works fine:

<img width="516" alt="Screenshot 2020-02-13 at 20 41 07" src="https://user-images.githubusercontent.com/1604351/74481728-8c689c80-4eb3-11ea-9820-fbbe977bc478.png">

This image is a screenshot of the generated file on windows, using Excel for Windows.

It seems that the OpenXLSX code using UTF-8 works fine on windows. The fact that the console output looks strange is an issue with the console app, not OpenXLSX.

The Windows OS uses UTF-16 internally. Conversion between UTF-8 and USF16 (or 32) can be done using the codecvt (in the c++ standard library since C++11) or a 3rd party library.

**Comment by duerk-de** [comment]
I do not have success in reading Korean strings out of an Excel file. This issue occurs where Korean characters are mixed with standard ones.

The xml data of sharedStrings looks like this:
```
<si>
  <r>
    <rPr>
      <sz val="12"/>
      <rFont val="Microsoft YaHei"/>
      <family val="2"/>
      <charset val="1"/>
    </rPr>
    <t xml:space="preserve">韓国語</t>
  </r>
  <r>
    <rPr>
      <sz val="12"/>
      <rFont val="Arial"/>
      <family val="2"/>
      <charset val="1"/>
    </rPr>
    <t xml:space="preserve">?</t>
  </r>
</si>
```

The xls document was created with Excel and edited with LibreOffice. It looks like some special formatting was automatically inserted and then OpenXLSX cannot read out the strings.

`OpenXLSX::Cell::valueType()` returns `OpenXLSX::XL:ValueType::Empty`.

**Comment by rageworx** [comment]
> 
> 
> I do not have success in reading Korean strings out of an Excel file. This issue occurs where Korean characters are mixed with standard ones.
> 
> The xml data of sharedStrings looks like this:
> 
> ```
> <si>
>   <r>
>     <rPr>
>       <sz val="12"/>
>       <rFont val="Microsoft YaHei"/>
>       <family val="2"/>
>       <charset val="1"/>
>     </rPr>
>     <t xml:space="preserve">韓国語</t>
>   </r>
>   <r>
>     <rPr>
>       <sz val="12"/>
>       <rFont val="Arial"/>
>       <family val="2"/>
>       <charset val="1"/>
>     </rPr>
>     <t xml:space="preserve">?</t>
>   </r>
> </si>
> ```
> 
> The xls document was created with Excel and edited with LibreOffice. It looks like some special formatting was automatically inserted and then OpenXLSX cannot read out the strings.
> 
> `OpenXLSX::Cell::valueType()` returns `OpenXLSX::XL:ValueType::Empty`.

You may need to understand "UTF-8" encoding instead wide charactor ( wchar_t ).
Most of XML may written in UTF-8 ( w/BOM or wo/BOM ), and most of koreans should be able to check length in mbsc instead of wcsc.

![image](https://user-images.githubusercontent.com/6948225/105451427-e545d500-5cbf-11eb-8e63-d83eaa469b11.png)

It's each these words:

- UTF-8 TEST Korean : 세상아 안녕?
- UCSC-2-LE TEST Korean : 세상아 안녕?

**Comment by duerk-de** [comment]
I'm sorry, I posted the wrong string. "韓国語" is Japanese, but there the same issue occurs.

This is not an encoding issue, there are no problems with the value of a cell. The problem is, OpenXLSX says the cell is empty although it is not: `OpenXLSX::Cell::valueType()` returns `OpenXLSX::XL:ValueType::Empty`.

Please have a look at my excerpt of sharedStrings.xml (as contained within the xlsx file), OpenXLSX is not accessing the `t` node.

In contrast to this, cell contents looking like this are working well with OpenXLSX:
```
<si>
  <t xml:space="preserve">韓国語</t>
</si>
```
