### ISSUE TITLE
Adding "mergeCells" to program corrupts .xlsx file

### ISSUE THREAD

**Issue by hopkinsa17** [troldal/OpenXLSX#286]
Hello all,

I'm working on an accounting program that writes various data to excel files and one of the files has a header row in which ten cells get merged into pairs (B1:C1, D1:E1, etc.) but no matter how I implement the "mergeCell" functionality, when I open the resulting workbook I get a messagebox that reads "We found a problem with some content in 'Worksheet.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes." Upon clicking next, I'm greeted by an empty workbook. I've tried several implementations so far and each one causes this messagebox. I'm writing data from a wxVector of wxVectors of wxStrings which is why I'm using "i" and "j" in the code below.

Here is the first implementation I tried:
```c++
// Merge current cell with one to its right:
OpenXLSX::XLCellReference start_ref((i + 1), (j + 1));
OpenXLSX::XLCellReference end_ref((i + 1), (j + 2));
std::string start = start_ref.address();
std::string end = end_ref.address();
std::string range = start + ":" + end;
sheet.mergeCells(range);
```

I also tried merging the cells explicitly after writing all the data:
```c++
// Merge header row cells:
sheet.mergeCells("B1:C1", OpenXLSX::XLEmptyHiddenCells);
sheet.mergeCells("D1:E1", OpenXLSX::XLEmptyHiddenCells);
sheet.mergeCells("F1:G1", OpenXLSX::XLEmptyHiddenCells);
sheet.mergeCells("H1:I1", OpenXLSX::XLEmptyHiddenCells);
sheet.mergeCells("J1:K1", OpenXLSX::XLEmptyHiddenCells);
```

Am I missing anything? Thank you in advance for your help!

**Comment by aral-matrix** [comment]
Hi @hopkinsa17  - from what I see you describe, you are not doing anything wrong. The mergeCells functionality is relatively new, and very few users so far have tested it. I may have implemented some faulty XML - my only available test platform is LibreOffice.

Could you test two things for me & let me know the results?
1) If you have it available, please check if LibreOffice can open your document with the expected results (that would exclude that the mergeCells somehow does something different on your system than on mine - although I would be surprised ;)
2) Could you check whether Demo10 creates a file that you can read / open in Microsoft (and - if possible - Libre) Office?

I have seen at least one screenshot from an MS Office user who opened Demo10 before with expected results, including the merged cells, so I did not expect any more issues.

Any chance that some other functionality in OpenXLSX is triggering this error?

**Comment by hopkinsa17** [comment]
I've established that it is "mergeCell" by applying formatting in stages; only when I added "mergeCell" functionality to my program did the file become corrupted. I installed LibreOffice and was able to open the document in LibreOffice Calc after implementing "mergeCell" in my program, so I suppose the issue must lie in the version of Office I'm using (Office 365);

I'm having trouble running the demos, when I try to create the demo project using cmake I get errors for each of the demos: "Target 'Demo#' links to: OpenXLSX::OpenXLSX but the target was not found." I'm not sure if building the demos will make any difference, because I think the issue is a result of how Office 365 reads the xml files compared to how LibreOffice, for example, reads the files. I really appreciate your help!

**Comment by hopkinsa17** [comment]
Okay the weirdest thing just happened. After opening the file in LibreOffice calc I was able to open the file and the cells were merged! I don't know how it started working but I'll re-generate the file and see if it opens now without going through LibreOffice first.

**Comment by aral-matrix** [comment]
Hey again! Are you saying it worked without *saving* in LibreOffice? That'd be weird :)

I wouldn't be surprised if LibreOffice repairs something that fixes it for MS Office though.

That would make my next suggested test step easier:

- reduce your bug to a workbook with a single worksheet (so we can be sure the XML is stored in sheet1.xml)
- unzip your program created file to a temp folder
- open xl/worksheets/sheet1.xml & copy-paste the mergeCells section here, like this one from Demo10:
```
<mergeCells count="2">
   <mergeCell ref="E4:G7"/>
   <mergeCell ref="J5:L8"/>
</mergeCells>
```
If you can lint-format it, that'd be great, but if you can't no biggie, I can do that.
- fix your buggy worksheet by opening it in LibreOffice & save it in LO, then confirm the error is gone in MS Office
- unzip the file saved by LibreOffice into a different temp folder, and extract the mergeCells XML like before, and post it here, and we'll compare them

Of course, you can always compare the (linted ;) XML yourself and see what "fixes" LibreOffice introduces.

Btw, I just pushed a minor bugfix - I noticed that when XLCellFormats::create is called without a template, I still had a "TODO" in the code to add meaningful defaults to an empty created format. 
However, that means that non-existing XML for style elements referred from an XLCellFormat (e.g. "fontId") would return ```XLInvalidStyleIndex```, which could cause an exception when used to access a style.

This *may* be what triggered MS Office, but I don't think it's the fix to your issue.

Still, I wouldn't be surprised if MS Office complains about a different section of the XML.

I am currently on vacation, so my apologies for responding a bit later than usual :)

**Comment by hopkinsa17** [comment]
No worries at all, I really appreciate you taking time out of your vacation to respond!

To clarify, I opened the file (with merged cells) in LibreOffice, fiddled with some unrelated formatting, and saved it using the .xlsx extension; then, I opened the file in MS Office 365 and it opened successfully, so I would agree that somehow LibreOffice fixed the xml to where Office 365 was able to read and open it.

Here's the original, unmodified xml mergeCells section:
`<mergeCells count="5">
    <mergeCell ref="B1:C1"/>
    <mergeCell ref="D1:E1"/>
    <mergeCell ref="F1:G1"/>
    <mergeCell ref="H1:I1"/>
    <mergeCell ref="J1:K1"/>
</mergeCells>`

and here is the xml mergeCells section after opening in LibreOffice, saving, and closing the file:
`<mergeCells count="5">
    <mergeCell ref="B1:C1"/>
    <mergeCell ref="D1:E1"/>
    <mergeCell ref="F1:G1"/>
    <mergeCell ref="H1:I1"/>
    <mergeCell ref="J1:K1"/>
</mergeCells>`

I didn't see any difference between the two, unfortunately. However, as part of my code I rename the sheet to be "Worksheet" instead of "Sheet1", and I haven't tried implementing mergeCell functionality without renaming the sheet so I'll give that a try next. I only changed the name of the sheet for aesthetic reasons, it really serves no functional purpose, so hopefully that makes some difference.

**Comment by aral-matrix** [comment]
Indeed, the mergeCells XML seems to be the same, so as I suspected, using the mergeCells function might be triggering an issue that exists elsewhere.
Are you creating the initial document entirely using OpenXLSX?
If so - could you create a copy of your project that you then proceed to modify by removing line after line from the XLSX document until you have a minimal (single sheet) XLSX document that MS Office will complain about? If you could share that here, I would have a look at it and hopefully find an error somewhere.

I suspect a broken reference to a style somewhere.

**Comment by hopkinsa17** [comment]
I don't know how much of a difference it makes, but I did identify one difference between the original xml file and the one that results from the xlsx file being saved in LibreOffice: the first line originally reads
```xml
<?xml version="1.0" encoding="UTF-8"?>
```
and after saving it reads
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
```
but otherwise I couldn't locate any other differences between the two, so adding the "standalone='yes'" flag must have some impact.

To answer your question, yes; I am creating the initial document entirely using OpenXLSX, and I'm curious: is there any way to programmatically add the "standalone='yes'" flag to the resulting xml file during runtime to avoid this issue? I'll work on making a minimal reproducible example to share here. Thank you so much for your help!

**Comment by aral-matrix** [comment]
yes you can create the standalone flag but it shouldn't make a difference.

Here's how:
```
   // header: XLXmlSavingDeclaration(std::string version, std::string encoding, bool standalone = XLXmlNotStandalone)
   XLXmlSavingDeclaration mySavingDeclaration ("1.0", "UTF-8", XLXmlStandalone);
   myDoc.setSavingDeclaration (mySavingDeclaration); // can't currently construct in-place because dummy me made this function take a const reference, which I believe does not work with a temporary object
```

Testing this now myself quickly. However, this part of the XML doesn't matter. The styles changes that I suspect are in a different file: xl/styles.xml

**Comment by hopkinsa17** [comment]
[Test.xlsx](https://github.com/user-attachments/files/17528055/Test.xlsx)
Here's the file I created with a minimal program that simply writes "Test string" to cell A1, then merges A1:B1, saves, and closes. I tried opening it in Excel and got the same error message. I'll try implementing the standalone flag and see if that makes any difference, thank you!

**Comment by hopkinsa17** [comment]
I took a look at the styles.xml file before and after saving in LibreOffice; the differences are numerous and striking; saving in LibreOffice completely rearranges and reconfigures the styles.xml file. I can provide both if it would be helpful.

**Comment by aral-matrix** [comment]
okay, so I am able to produce the exact same file as you uploaded with the following program
```
#include <iostream>
#include <OpenXLSX.hpp>

using namespace OpenXLSX;

int main()
{
	XLDocument doc{};
	doc.create("./Demo10.xlsx", XLForceOverwrite);
    auto wks = doc.workbook().worksheet(1);
    wks.cell("A1") = "Test data";
    wks.mergeCells( "A1:B1" );
    doc.save();
	doc.close();

	return 0;
}
```

So that's good, that means this is a general bug I put in somewhere (read: incompatibility with MS Office) and not some weird thing that only occurs in your configuration.

Just saw your last message: yes please, if you could upload the file "repaired" by LibreOffice, I'll compare that myself, I know LO rearranges everything but I hope I am able to spot the relevant detail

**Comment by aral-matrix** [comment]
To be clear, I am interested in the whole Test.xlsx as saved by LO, and as MS Office would open it without complaints

**Comment by aral-matrix** [comment]
I am surprised this hasn't popped up before because there's plenty of MS office users here...

**Comment by hopkinsa17** [comment]
I can't upload the before and after styles.xml files but here is the file after opening and saving in LO:
[Test.xlsx](https://github.com/user-attachments/files/17528182/Test.xlsx)
I don't know if this makes any difference but I wrote both the original program and the minimal testing program in MS Visual Studio 2022 running on Windows 11 Pro.

**Comment by aral-matrix** [comment]
mhh - I don't spot anything obvious, but a lot of "could be the issue" - could I ask you to slowly eliminate the differences between the pre-repair and post repair XML over a few days, with my suggestions? It'll take a few days because it's getting late here and I won't always find time to respond with the next step.

The first step - since your initial bugged document is not using styles at all - would be to try and replace the styles.xml in the broken document with the one from the repaired document, zip it back up and see if that helps:
```
mkdir broken
cd broken
unzip ../Test.xlsx
cd ..
mkdir repaired
cd repaired
unzip ../Test-repaired.xlsx
cp xl/styles.xml ../broken/xl/
cd ../broken
zip -r ../Test-manual.xlsx
```
and then open Test-manual.xlsx in MS Office.

I know the windows console commands are a bit different, but you get the picture. Here's hoping that whatever means you have to zip the XLSX back up is compatible with office :)

**Comment by hopkinsa17** [comment]
The exact error message I get when I try to open the original "test.xlsx" file in Excel is:

Excel was able to open the file by repairing or removing the unreadable content. Replaced Part: /xl/worksheets/sheet1.xml part with XML error. Load error. Line 2, column 958

I'll try and zip the repaired styles.xml file into the original excel file, thank you so much for your help!

**Comment by aral-matrix** [comment]
of course if you feel comfortable, you could always try and edit the xml manually to align the files until the bug is gone & then we'll know what the last step that "fixed it" will have been.

My order of business would be:
1) replace styles.xml
2) replace sharedStrings.xml, and edit in the worksheet the cell 1 value XML to ```<v>0</v>``` (the repaired version of sharedStrings has the empty string at index 0 removed so "Test data" slipped to index 0
3) replace sheet1.xml

If step no. 3 fixes the issue, I suspect that a merged Cell (and this would explain how merging cells triggers this) somehow *requires* that an entry for at least the last cell in the merged range exists. Because I see LibreOffice added an entry for cell B1 with the same style reference.
3) Actually as I just looked at this, it feels like a strong candidate for the problem: In sheet

**Comment by aral-matrix** [comment]
In this case, since you got an error message specifically about the sheet1.xml file, I'd start by editing in an entry for cell B1 like so:
from
```
<row r="1"><c r="A1" t="s"><v>1</v></c></row>
```
to
```
<row r="1"><c r="A1" t="s"><v>1</v></c><c r="B1" s="1"/></row>
```

**Comment by aral-matrix** [comment]
LibreOffice definitely creates an XML entry for every single cell that is part of the merge, with nothing but a reference to the cell itself and to the style of the top left corner of the merge.

So basically I might not have noticed because when I was using merges, entries for all the merged cells already existed. That would explain why you are the first to report it. I'll prepare a patch anticipating that this is the root cause.

**Comment by aral-matrix** [comment]
In the meantime, you can try to use XLEmptyHiddenCells with mergeCells:
```
    wks.mergeCells( "A1:B1", XLEmptyHiddenCells );
```
This invokes XLCell::clear, and by dereferencing the range iterator for each cell in this way it creates an empty cell entry.

If this resolves the MS Office complaint, we would know that an empty cell entry is enough, and the style attribute is not required to resolve the bug.

**Comment by aral-matrix** [comment]
I just pushed an update to (my development branch)[https://github.com/troldal/OpenXLSX/tree/development-aral]

**Comment by hopkinsa17** [comment]
When I tried explicitly merging the cells by address range (the second block of code in my original post), I passed "XLEmptyHiddenCells" as an argument; I tried both variations of the explicit merge (with and without "XLEmptyHiddenCells") and both ways produced the same result.

I tried the modification to sheet1.xml you recommended:
```xml
<row r="1"><c r="A1" t="s"><v>1</v></c><c r="B1" s="1"/></row>
```
and then tried zipping the folder using 7zip, changing the extension from ".zip" to ".xlsx" and opening in Excel but it didn't work, I got an error message saying the document was unrecoverable. I'll download and test the update and let you know how it goes, thank you so much for all your help!

**Comment by hopkinsa17** [comment]
@aral-matrix I downloaded, built, and implemented the updated OpenXLSX library from your development branch and unfortunately the error on opening the resulting file in Excel persists. For the time being I'll just comment out the sequence that uses mergeCell and continue with the rest of the project, thank you so much for your help

**Comment by aral-matrix** [comment]
I am sorry about this, without having a Microsoft Office at my disposal, debugging this will be a bit slower than desirable.
Since your own zipping up the archive after modification did not work, I can create a couple of test files for you over the next days to try and find which part gets rid of the error, but it'll take a while since as I said I am on vacation.

**Comment by hopkinsa17** [comment]
I've successfully implemented the updated OpenXLSX library in my program but still have had no luck merging the cells and opening the original file in MS Excel :( Any progress on your end?

**Comment by hopkinsa17** [comment]
Please, enjoy your vacation! This project is nothing urgent, just something I work on in my free time. I am in no rush to get this program up and running.

**Comment by aral-matrix** [comment]
I am waiting for an opportunity to use a friend's computer with MS Excel on it. But if you were able to re-zip an archive now, maybe you can also make some progress in manually merging the repaired file components until the error goes away. 
Will let you know when I get a chance to work on this.

**Comment by aral-matrix** [comment]
Okay, with the help of a friend and his MS Excel, I believe I was able to solve this. Have a look at the latest development-aral commits 5d13a7d1718cf5c95d66cb0d7cdba6e2c5e2008e and dd2ac495a789d3bec11e0e69189ab52644a934a2 - as stupid as it is, MS Excel took issue with the "pageMargins" XML node being between the ```sheetData``` and the ```mergeCells``` nodes. So there was no *actual* error in the document, just a stupid rule that Excel imposes on the "correct order" of root level XML nodes.

I hope you will be able to confirm this fix. Feedback appreciated!

**Comment by hopkinsa17** [comment]
I downloaded, built, and implemented the updated library but still get an error when opening the file in MS Excel first. Is there an easier way to update a locally installed library than deleting it, building the newly downloaded one, and implementing it? I'll try my method one more time and let you know the results, I greatly appreciate your help with this.

**Comment by aral-matrix** [comment]
I am a bit surprised that you are still getting an error because I was able to reproduce your error with my friend's windows system, and when I changed the XML, the error went away on MS Office. That's a pity.

Having ditched Windows a long time ago it's hard for me to give advice on such heterogenous environments as Windows (basically every single windows user has a deviating setup in some ways), but what I would do depends on whether you have git available.

With git, you'd just keep a project folder and try to verify basic functionality with the Demo programs (e.g. Demo10, which applies merged cells).

I am assuming you are not using git (because it's a bit of a learning curve to get used to it), so I would:
* Open https://github.com/troldal/OpenXLSX/tree/development-aral
* ```<> Code v``` -> ```Download ZIP```
* unzip that archive
* cd into the new directory
* ```cmake .```
* ```cmake --build .```
* ```output/Demo10```
* and then attempt to open the ```Demo10.xlsx``` file & see if it produces an error or opens correctly

If that does not work, you could replace the contents of ```Examples/Demo10.cpp``` with the minimal main function I mentioned above, recompile and test that ```Demo10.xlsx``` output. Minimal example quoted again for convenience below.

With that Example program I get this file here, which *only* differs from your "broken" example in that the ```<mergeCells>``` element moved up one node, before the ```<pageMargins>``` node. On my friends' MS Excel, this was what made the error disappear. 
[Test-new.xlsx should open without error](https://github.com/user-attachments/files/17535375/Test-new.xlsx)

Note: the attached XLSX file has the xl/worksheets/sheet1.xml pretty-formatted for easier comparison with a textual diff-tool. Therefore I will also attach your original Test.xlsx with the same formatting here, so you can test both and compare the zip contents:
[Test-pretty.xlsx should produce the known error](https://github.com/user-attachments/files/17535379/Test-pretty.xlsx)

Minimal example to reproduce ```Test.xlsx```:
```
#include <iostream>
#include <OpenXLSX.hpp>

using namespace OpenXLSX;

int main()
{
	XLDocument doc{};
	doc.create("./Demo10.xlsx", XLForceOverwrite);
	auto wks = doc.workbook().worksheet(1);
	wks.cell("A1") = "Test data";
	wks.mergeCells( "A1:B1" );
	doc.save();
	doc.close();

	return 0;
}
```

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by aral-matrix** [comment]
@troldal thanks for the quick reaction. I just logged in from mobile to delete the spam but you beat me to it :)

**Comment by troldal** [comment]
Yeah, it just looked highly suspicious, so I just deleted them before anyone fell for it.

**Comment by hopkinsa17** [comment]
I built and ran Demo10 using CMake through the command prompt and was able to open the Demo10.xlsx file without issues! I'm not sure how building through cmd differs from using the CMake GUI, but I'll implement the library I just built and see if it resolves my problem. Thank you for all your help!

**Comment by aral-matrix** [comment]
hi again @hopkinsa17 - I am glad to hear that it appears we solved the mergeCells issue. Thank you for your patience & help with narrowing down the root cause.
With regards to the error you were seeing with your own project, I would not dismiss the possibility that I made another mistake and you have a 2nd, unrelated error. I'll try to resolve that quickly should it persist.

**Comment by hopkinsa17** [comment]
I've implemented the updated library in my project and while I still get the errors "We found a problem with some content in 'Worksheet.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes." and upon clicking yes, "Removed Part: /xl/styles.xml part with XML error. (Styles) Load error. Line 6, column 0. Repaired Records: Cell information from /xl/worksheets/sheet1.xml part", the sheet data loads with the specified cells merged as expected. Somehow, all formatting gets removed from the sheet, however. I suppose the "repaired" part(s) in the underlying XML documents must somehow dictate the formatting that is lost in recovery. Thank you so much for your help!

**Comment by hopkinsa17** [comment]
I don't know if it has any bearing on the situation but I haven't been able to get the updated library to produce a new OpenXLSXd.dll file so I've been using the existing one from the old library. If it's salient, any guidance on producing that file would be greatly appreciated, and I'll continue to tinker with the underlying .xml files for "Worksheet.xlsx" to see if I can figure out what's going on there. Thank you!

**Comment by aral-matrix** [comment]
1) xl/styles.xml describes each and *all* styles in the document, so if MS Office decides to remove that, the loss of all formatting information is inevitable. Each style gets an identifying index (XLStyleIndex in my implementation) in that file, and a cell only refers to that index by ```style=#``` where # is the index of the cell Format, which can further refer to the index of a font, a filling, etc.
However, since you said you were able to open Demo10.xlsx without errors, it appears to be not a quite-so-generic error as with the mergeCells.
I don't know at what point MS Office triggers, but in theory it is possible using the existing code to generate a reference to a style index that does not actually exist, and that would be entirely avoidable without me doing anything.
If you can upload an example XLSX file (the smaller the better) upon which said error with ```xl/styles.xml``` occurs for you, I can have a look.

2) I am really a bit weak on the windows side, but shouldn't cmake produce an OpenXLSX.dll file in the output folder at ```output/OpenXLSX.dll```? It definitely puts the library file there for me on Linux (but not as a DLL, obviously).

**Comment by liu20** [comment]
in excel2016  ,node “mergeCells” must be after “sheetData”
change XLSheet.cpp：
```
if (mergeCellsNode.empty())
            mergeCellsNode = xmlDocument().document_element().append_child("mergeCells");
```
to：
```
if (mergeCellsNode.empty()) {
            auto sheetDataNode  = xmlDocument().document_element().child("sheetData");
            mergeCellsNode = xmlDocument().document_element().insert_child_after("mergeCells", sheetDataNode);
        }
```

**Comment by hopkinsa17** [comment]
@aral-matrix I don't know if it's the same thing but I have a "nowide.dll" in "output\debug"; I've tried explicitly setting option(BUILD_SHARED_LIBS ON) in the CMakeLists.txt file in the root OpenXLSX folder but that doesn't seem to have produced an "OpenXLSX.dll" file so I'm not really sure what else to do. When I open the OpenXLSX.sln file in the root folder I am only able to build all if I exclude OpenXLSXTests, for some reason that project gives me an error on build. I'm not sure if I need an updated "OpenXLSX.dll" file anyhow, so I'll proceed with the original one for now. 

@liu20 I'll give your suggestion a try and see how it goes, and let you all know the result. Thank you!

**Comment by hopkinsa17** [comment]
@liu20 here's what I have in XLSheet.cpp:
```c++
XMLNode mergeCellsNode = xmlDocument().document_element().child("mergeCells");
if (mergeCellsNode.empty()) {
    // ===== 2024-10-27 BUGFIX: MS Office does not tolerate page formatting nodes before the mergeCells node,
    //   therefore, insert the mergeCells node directly after the sheetData node
    XMLNode sheetDataNode = xmlDocument().document_element().child("sheetData");
    if (sheetDataNode.empty())
        throw XLInternalError("XLWorksheet::merges: sheetData XML node is not initialized. Can not proceed.");
    mergeCellsNode = xmlDocument().document_element().insert_child_after("mergeCells", sheetDataNode);
}
m_merges = XLMergeCells(mergeCellsNode);
```
It looks like your suggestion was already implemented before I came along with a few extra lines; I'm not nearly knowledgeable enough in this regard to be able to decipher precisely what each line is doing, but as far as I can tell it's doing what it should..? Idk, I really appreciate your input though!

**Comment by hopkinsa17** [comment]
@aral-matrix I don't know if this makes any difference but after looking at the mergeCell function definition in XLSheet.cpp, I noticed that the first argument should be an instance of XLCellRange, while I'm passing a "const char[6]"; does that make any difference, and is it worth trying to initialize an XLCellRange object to pass to the mergeCell function instead of the "const char[6]" I'm currently using?

**Comment by liu20** [comment]
> @aral-matrix I don't know if this makes any difference but after looking at the mergeCell function definition in XLSheet.cpp, I noticed that the first argument should be an instance of XLCellRange, while I'm passing a "const char[6]"; does that make any difference, and is it worth trying to initialize an XLCellRange object to pass to the mergeCell function instead of the "const char[6]" I'm currently using?
> 
> Last note before I call it a day: I updated the minimal program I used earlier to generate an error-producing file to integrate the updated library and it opens without issue, but the text isn't centered in the merged cell range as it should be; does this still qualify? Here is the file: [Test.xlsx](https://github.com/user-attachments/files/17551374/Test.xlsx)
> 
> Okay I promise this is my last thought of the day: what if I merge the cells, then afterwards apply formatting? Would that work?

Merging cells and then applying the formatting works fine. But the latest commit has a problem

**Comment by aral-matrix** [comment]
> in excel2016 ,node “mergeCells” must be after “sheetData” change XLSheet.cpp：
> 
> ```
> if (mergeCellsNode.empty())
>             mergeCellsNode = xmlDocument().document_element().append_child("mergeCells");
> ```
> 
> to：
> 
> ```
> if (mergeCellsNode.empty()) {
>             auto sheetDataNode  = xmlDocument().document_element().child("sheetData");
>             mergeCellsNode = xmlDocument().document_element().insert_child_after("mergeCells", sheetDataNode);
>         }
> ```

Thank you @liu20 - I already implemented this fix 2 days ago in the development-aral branch and will merge it into master within the next days.

**Comment by aral-matrix** [comment]
> @aral-matrix I don't know if this makes any difference but after looking at the mergeCell function definition in XLSheet.cpp, I noticed that the first argument should be an instance of XLCellRange, while I'm passing a "const char[6]"; does that make any difference

No, if you look closely, you will see there is a wrapper function that takes a string (which accepts const chars) and creates a cell range from it. So you are all good.

> Last note before I call it a day: I updated the minimal program I used earlier to generate an error-producing file to integrate the updated library and it opens without issue, but the text isn't centered in the merged cell range as it should be; does this still qualify? Here is the file: [Test.xlsx](https://github.com/user-attachments/files/17551374/Test.xlsx)

I think considering I am still on vacation, maybe this is best answered by looking at the mergeCells examples in Demo10.cpp - it applies formatting as well.

This ticket is becoming a bit crowded with mixed issues. I think the mergeCells issues is resolved (in development-aral) & maybe you could open another issue for the formatting, should a look at Demo10 not help resolve it?
> 
> Okay I promise this is my last thought of the day: what if I merge the cells, then afterwards apply formatting? Would that work?

**Comment by hopkinsa17** [comment]
That makes sense, I apologize for taking up so much of your time with this; I'll take closer look at the Demo10 xml files and see if I can identify what differs between those and my own files. Thank you so much for all your help!
