### ISSUE TITLE
Missing include file openxslsx_export.h

### ISSUE THREAD

**Issue by arochettesteinberg** [troldal/OpenXLSX#31]
Hi,

that sounds already like a stupid question but I'm not able to compile your library due to a seemingly missing include file "openxlsx_export.h". It's being referred to in pretty much every other include file.

Thanks!

**Comment by arochettesteinberg** [comment]
Ok just had to build it from scratch with VS2019

**Comment by troldal** [comment]
Hi @arochettesteinberg 

The project has to be configured using CMake. The CMake tool will auto-generate the “openxlsx_export.h” according to your operating system.

Since 2017, Visual Studio has supported CMake projects natively. But if you are going to build OpenXLSX in another IDE or on another platform, you will need to configure the project using CMake yourself.
