### ISSUE TITLE
m_sheetNameNodes not being populated properly?

### ISSUE THREAD

**Issue by maddy15791** [troldal/OpenXLSX#4]
![image](https://user-images.githubusercontent.com/47287769/52181431-828f6200-27a6-11e9-8cbf-b51178053726.png)

dear @troldal , When i try to open an existing workbook with multiple sheets, The plugin properly finds the sheets and populates it under m_sheetNodes, but m_sheetnameNodes is not populated as expected(test1 which is an existing sheet is missing, sheet1 is something that i added using the plugin)

Is this expected?what is the significance of m_sheetNameNodes? what does it contain? 

the exception for missing sheet is thrown inside this function

```
XLWorksheet * XLWorkbook::Worksheet(const std::string &sheetName)
{
    if (m_sheets.find(sheetName) == m_sheets.end()) throw std::range_error("Sheet \"" + sheetName + "\" does not exist");

    if (m_sheets.at(sheetName) == nullptr) {
        m_sheets.at(sheetName) = make_unique<XLWorksheet>(*this, sheetName, **m_sheetPaths.at(sheetName))**;
        m_childXmlDocuments.at(m_sheetPaths.at(sheetName)) = m_sheets.at(sheetName).get();
    }
```

Thanks for the awesome job!!!

**Comment by troldal** [comment]
Hello @maddy15791. 

I'm glad you like it. And thanks for the feedback.

Actually, I'm in the process of making some rather large changes. One of those are to reduce the number of internal data structures and instead rely only on the underlying XML data. For that reason, the member functions you refer to has been changed.

I am not ready to merge in to the master just yet, but if you try to compile the PIMPL branch instead of the master, things should work out.

I would be grateful if you could give me some feedback after building the PIMPL branch.
