### ISSUE TITLE
a note about xlsxio

### ISSUE THREAD

**Issue by playgithub** [troldal/OpenXLSX#45]
Encounter some xlsx files that can not be parsed by XLNT, but can be parsed by the c lib: https://github.com/brechtsanders/xlsxio

**Comment by troldal** [comment]
Hi @playgithub 

Can you provide some details:
1. I assume that you meant OpenXLSX, not XLNT?
2. Do you have some sample files that can be parsed by xlsIO, but not Open XLSX?

**Comment by playgithub** [comment]
> 1. I assume that you meant OpenXLSX, not XLNT?

As far as I remeber, I tried both.


> 2. Do you have some sample files that can be parsed by xlsIO, but not Open XLSX?

[sample.zip](https://github.com/troldal/OpenXLSX/files/4783942/sample.zip)
In Chinese encoded in GB2312

**Comment by troldal** [comment]
The sample file you sent is in .xls format (the legacy Excel file format) rather than .xlsx (introduced in Excel 2007). It was never the intent that OpenXLSX should support .xls files as the file format is obsolete. Only .xlsx files are supported. This is not a bug, but a design decision.

Also, .xlsx files must be encoded in UTF-8.

**Comment by playgithub** [comment]
Sorry, too hard to remeber.
