### ISSUE TITLE
Numbers below 0.003 can not be recognized as float.

### ISSUE THREAD

**Issue by wanzhiyu** [troldal/OpenXLSX#46]
Environment: Windows 10, Office 365

For example, here is a excel file created by office 365.
[NumberTest.xlsx](https://github.com/troldal/OpenXLSX/files/4774413/NumberTest.xlsx)

In this file, numbers below 0.003 can not be recognized as float.
"0.002" can only be read by "Get<**int**>()" and the result is "2" which is obviously wrong.
"0.001" can only be read by "Get<**int**>()" and the result is "1" which is obviously wrong.
"0.0021" can not be read by "Get<**int**>()" or "Get<**float**>()" and I don't know how to read this number.

All these numbers cannot be read by "Get<**float**>()".I tried alot of times. And it throws an exception:"XLException".

**Comment by troldal** [comment]
Hi @wanzhiyu 

Thanks for highlighting this. I have updated the repo with a bug fix. It was a small bug in a function that determines if a number is an int or a float. The function didn't handle scientific notation properly. It turns out that Excel stores numbers below 0.003 in scientific notation (e.g. 0.002 as stored as 2E-3)

**Comment by wanzhiyu** [comment]
Yes, it works now. Thanks a lot!
