### ISSUE TITLE
can't find string_view

### ISSUE THREAD

**Issue by Huang88888888Fei** [troldal/OpenXLSX#56]
Hi, thanks for your excellent work! But I use cmake+vs 2015 , it produce an error "can't find <string_view>" . I know it the feature of c++17, so I want to ask: how to fix it or which version can compile with vs2015?

**Comment by troldal** [comment]
Hi @Huang88888888Fei,

There are various non-standard implementations of std::string_view, e.g. https://github.com/martinmoene/string-view-lite.
However, I'm not sure that it will help you much, if you don't have a C++17 compliant compiler already. OpenXLSX uses other C++17 features, for example "constexpr if", which is a language-level feature rather than a library feature, and hence not easily replaceable. 

Is there a reason that you want to use VS2015 rather than the latest version?

**Comment by Huang88888888Fei** [comment]
Thanks for your reply. I think you are right. If I don't use c++17, there are a lot of changes to be made. I'll just install the latest version.
