### ISSUE TITLE
Remove @

### ISSUE THREAD

**Issue by egorpugin** [troldal/OpenXLSX#7]
Hi!

Is it possible to remove @ from dirs? It is very uncommon.

**Comment by troldal** [comment]
Hi @egorpugin,

The reason I use @ in the folder names, is to ensure that directories are sorted such that source folders appear at the top. So far, I haven't experienced any issues with build systems etc. complaining about the @ sign.

If you experience any issues related to the @ sign, please let me know; then I will consider removing. Otherwise, I will prefer to leave it in.

**Comment by egorpugin** [comment]
Ok, it's up to you. I'm also fine with @.
