### ISSUE TITLE
Compiling on Windows with MSVC gives "openxlsx_exports.h" not found

### ISSUE THREAD

**Issue by athathdev** [troldal/OpenXLSX#71]
I tried these commands in Windows

mkdir build
cd build
cmake ..
cmake --build . --target install

The project builds successfully but during install, gives the error
"openxlsx_exports.h" not found

Edit: I get the same error in Linux (Ubuntu) using GCC.

**Comment by ExtremeOne** [comment]
I had the same problems as you.
These steps solved this problem for me personally: 
1. Open CMake (GUI)
2. Enter the root of the OpenXLSX directory (for me it's F:/OpenXLSX-master) as source code
3. Directory to build binaries (for me it's: F:/OpenXLSX-master/build)
4. Then click "Configure"
5. Select a project generator and platform (for me it's: Visual Studio 16 2019 and x64 or empty)
6. After that, due to building errors, a list of names with values (check boxes) is displayed. Make sure to uncheck everything except FETCHCONTENT_QUIET and BUILD_OBJECT_LIB
7. Then click "Configure" again, and then "Generate"
8. To open a project in Visual Studio click on "Open Project", and build it
You should have everything you need now.

You can create an auxiliary folder to use OpenXLSX:
In the created directory e.g OpenXLSX you need to copy: 
- the content of the OpenXLSX-master/build/output/debug folder
- the content of the OpenXLSX-master/library folder
- the "OpenXLSX-Exports.hpp" file from OpenXLSX-master/build/library

To be configured with a visual studio:
- Open Folder in File Explorer and paste your auxiliary folder OpenXLSX
- Properties/Configuration Properties/General - C++ Language Standard - select C++17
- Properties/C/C++/General - Additional Include Directories - add "$(ProjectDir)OpenXLSX" path
- Properties/Linker/General - Additional Library Directories - add "$(ProjectDir)OpenXLSX" path
- Properties/Linker/Input - Additional Dependencies - add "OpenXLSX-sharedd.lib" file name

I hope it was helpful.

Kind regards,
Nemanja

**Comment by troldal** [comment]
Installation should work now.
However, it is much easier to include OpenXLSX as a subdirectory to a CMake project, so I suggest you do that instead.
